#!/usr/bin/env python3
"""
immich_sync.py — Sync classified videos to Immich Tags and Albums.

Features:
- Queries Immich REST API for asset catalog.
- Maps local disk paths / filenames to Immich Asset IDs.
- Tags every video with its classification:
    • Tag: "video:static"
    • Tag: "video:review"
    • Tag: "video:dynamic"
- Populates corresponding Immich Albums:
    • [Static] Videos
    • [Review] Videos
    • [Dynamic] Videos
- Supports tagging extracted images with "video:extracted".
- Supports --dry-run to preview actions safely before modifying Immich.

Usage:
    python immich_sync.py [options]

Options:
    --api-url URL        Immich URL (or set IMMICH_API_URL in .env)
    --api-key KEY        Immich API Key (or set IMMICH_API_KEY in .env)
    --db PATH            Path to SQLite checkpoint (default: ./detection_checkpoint.sqlite)
    --no-tags            Skip adding tags to assets
    --no-albums          Skip adding assets to albums
    --include-dynamic    Also tag and create album for dynamic videos
    --dry-run            Preview tag and album operations without modifying Immich
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from core import Checkpoint, format_bytes

# ─────────────────────────────────────────────
# IMMICH API CLIENT
# ─────────────────────────────────────────────

class ImmichClient:
    def __init__(self, base_url: str, api_key: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.headers = {
            "x-api-key": self.api_key,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def _request(self, method: str, endpoint: str, data: Optional[dict] = None) -> Any:
        url = f"{self.base_url}{endpoint}"
        body = json.dumps(data).encode("utf-8") if data is not None else None
        req = urllib.request.Request(url, data=body, headers=self.headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                resp_text = resp.read().decode("utf-8")
                return json.loads(resp_text) if resp_text else None
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8")
            raise RuntimeError(f"Immich API HTTP {e.code} ({e.reason}) on {method} {endpoint}: {err_body}")
        except Exception as e:
            raise RuntimeError(f"Immich API request failed ({method} {endpoint}): {e}")

    def ping(self) -> dict:
        """Verifies server connectivity and authentication."""
        return self._request("GET", "/api/server/version")

    def get_all_video_assets(self) -> List[Dict[str, Any]]:
        """Retrieves all video assets from Immich library."""
        videos = []
        page = 1
        page_size = 1000

        print("📡 Fetching video catalog from Immich API...")
        while True:
            payload = {
                "type": "VIDEO",
                "size": page_size,
                "page": page,
                "withExif": True,
                "isVisible": True,
            }
            res = self._request("POST", "/api/search/metadata", payload)
            assets = res.get("assets", {}).get("items", []) if isinstance(res, dict) else []
            if not assets:
                break
            videos.extend(assets)
            if len(assets) < page_size:
                break
            page += 1
            print(f"   Fetched {len(videos)} videos so far (page {page})...")

        print(f"✅ Found {len(videos)} total video assets in Immich.")
        return videos

    # ─────────────────────────────────────────────
    # ALBUMS API
    # ─────────────────────────────────────────────

    def get_albums(self) -> List[Dict[str, Any]]:
        """Retrieves existing albums."""
        return self._request("GET", "/api/albums") or []

    def get_album(self, album_id: str) -> Dict[str, Any]:
        """Retrieves album details including asset list."""
        return self._request("GET", f"/api/albums/{album_id}") or {}

    def create_album(self, album_name: str) -> Dict[str, Any]:
        """Creates a new album."""
        return self._request("POST", "/api/albums", {"albumName": album_name, "description": "Auto-generated by immich-static"})

    def get_album_assets(self, album_id: str) -> Set[str]:
        """Gets all asset IDs currently in an album."""
        album = self._request("GET", f"/api/albums/{album_id}") or {}
        assets = album.get("assets", [])
        return {a["id"] for a in assets if "id" in a}

    def add_assets_to_album(self, album_id: str, asset_ids: List[str]) -> Any:
        """Adds asset IDs to an album in batches of 500."""
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            self._request("PUT", f"/api/albums/{album_id}/assets", {"ids": batch})

    # ─────────────────────────────────────────────
    # TAGS API
    # ─────────────────────────────────────────────

    def get_tags(self) -> List[Dict[str, Any]]:
        """Retrieves all tags."""
        try:
            return self._request("GET", "/api/tags") or []
        except Exception:
            return []

    def create_tag(self, tag_name: str) -> Dict[str, Any]:
        """Creates a new tag."""
        try:
            return self._request("POST", "/api/tags", {"name": tag_name, "type": "CUSTOM"})
        except Exception:
            # Fallback for older versions
            return self._request("POST", "/api/tags", {"name": tag_name})

    def untag_assets(self, tag_id: str, asset_ids: List[str]) -> Any:
        """Removes a tag from asset IDs in batches."""
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            try:
                self._request("DELETE", f"/api/tags/{tag_id}/assets", {"ids": batch})
            except Exception:
                pass

    def tag_assets(self, tag_id: str, asset_ids: List[str]) -> Any:
        """Tags asset IDs in batches of 500 with response verification and retries."""
        import time
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            res = None
            try:
                res = self._request("PUT", f"/api/tags/{tag_id}/assets", {"ids": batch})
            except Exception:
                try:
                    res = self._request("POST", f"/api/tags/{tag_id}/assets", {"ids": batch})
                except Exception as e:
                    print(f"⚠️  Tag request error: {e}")

            # Check for any items that failed
            if isinstance(res, list):
                failed = [
                    item.get("id") for item in res
                    if isinstance(item, dict) and not item.get("success", True) and item.get("id")
                ]
                if failed:
                    time.sleep(1.0)
                    try:
                        self._request("PUT", f"/api/tags/{tag_id}/assets", {"ids": failed})
                    except Exception:
                        pass
        return res

    def upload_asset(self, file_path: Path, created_at: Optional[str] = None) -> Optional[Dict[str, Any]]:
        """Uploads a still frame image to Immich."""
        import mimetypes
        import uuid
        from datetime import datetime, timezone

        boundary = f"----WebKitFormBoundary{uuid.uuid4().hex}"
        filename = file_path.name
        mime_type = mimetypes.guess_type(str(file_path))[0] or "image/jpeg"
        with open(file_path, "rb") as f:
            file_data = f.read()

        # Format ISO8601 UTC timestamp with Z
        if created_at:
            try:
                # If already string, try parsing or ensure ends with Z
                if isinstance(created_at, (int, float)):
                    dt = datetime.fromtimestamp(created_at, tz=timezone.utc)
                    utc_time_str = dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
                else:
                    dt = datetime.fromisoformat(created_at.replace("Z", "+00:00")).astimezone(timezone.utc)
                    utc_time_str = dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
            except Exception:
                utc_time_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
        else:
            utc_time_str = datetime.fromtimestamp(file_path.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

        device_asset_id = f"{file_path.stem}-{uuid.uuid4().hex[:8]}"

        parts = []
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"deviceAssetId\"\r\n\r\n{device_asset_id}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"deviceId\"\r\n\r\nimmich-static\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileCreatedAt\"\r\n\r\n{utc_time_str}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileModifiedAt\"\r\n\r\n{utc_time_str}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"isFavorite\"\r\n\r\nfalse\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"assetData\"; filename=\"{filename}\"\r\nContent-Type: {mime_type}\r\n\r\n".encode("utf-8"))
        parts.append(file_data)
        parts.append(f"\r\n--{boundary}--\r\n".encode("utf-8"))

        body = b"".join(parts)
        headers = {
            "x-api-key": self.api_key,
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "Accept": "application/json",
        }
        url = f"{self.base_url}/api/assets"
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                res_text = resp.read().decode("utf-8")
                return json.loads(res_text) if res_text else None
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8")
            raise RuntimeError(f"Immich upload failed ({e.code} {e.reason}): {err_msg}")
        except Exception as e:
            raise RuntimeError(f"Immich upload request failed: {e}")


# ─────────────────────────────────────────────
# SYNC LOGIC (TAGS & ALBUMS)
# ─────────────────────────────────────────────

def sync_immich(
    client: ImmichClient,
    ckpt: Checkpoint,
    dry_run: bool = False,
    sync_tags: bool = True,
    sync_albums: bool = True,
    include_dynamic: bool = False
):
    # 1. Fetch Immich Assets & Build Lookup Maps
    immich_videos = client.get_all_video_assets()

    path_to_asset: Dict[str, Dict[str, Any]] = {}
    name_to_assets: Dict[str, List[Dict[str, Any]]] = {}

    for asset in immich_videos:
        aid = asset.get("id")
        orig_path = asset.get("originalPath") or ""
        orig_name = asset.get("originalFileName") or Path(orig_path).name

        if orig_path:
            norm_path = os.path.normpath(orig_path)
            path_to_asset[norm_path] = asset
            path_to_asset[Path(orig_path).name] = asset

        if orig_name:
            name_to_assets.setdefault(orig_name, []).append(asset)

    # 2. Match Checkpoint Entries
    all_rows = ckpt.all_rows()
    print(f"📊 Checkpoint contains {len(all_rows)} classified files.")

    grouped_asset_ids: Dict[str, List[str]] = {
        "static": [],
        "review": [],
        "dynamic": [],
    }

    matched_count = 0
    unmatched_count = 0

    for r in all_rows:
        decision = r.get("decision")
        if decision not in ("static", "review", "dynamic"):
            continue
        if decision == "dynamic" and not include_dynamic:
            continue

        aid = r.get("asset_id")
        if aid and aid in {a["id"] for a in immich_videos}:
            grouped_asset_ids[decision].append(aid)
            matched_count += 1
            continue

        filename_str = r.get("filename", "")
        file_path = Path(filename_str)
        file_name = file_path.name
        matched_asset = None

        norm_full = os.path.normpath(filename_str)
        if norm_full in path_to_asset:
            matched_asset = path_to_asset[norm_full]
        elif file_name in name_to_assets and len(name_to_assets[file_name]) == 1:
            matched_asset = name_to_assets[file_name][0]
        else:
            for p, a in path_to_asset.items():
                if filename_str.endswith(p) or p.endswith(str(file_path.name)):
                    matched_asset = a
                    break

        if matched_asset:
            aid = matched_asset["id"]
            grouped_asset_ids[decision].append(aid)
            matched_count += 1
            if not r.get("asset_id"):
                r["asset_id"] = aid
                ckpt.record(aid, r)
        else:
            unmatched_count += 1

    print(f"🔗 Match Results:")
    print(f"   • Matched Immich Assets : {matched_count}")
    print(f"   • Unmatched Local Files : {unmatched_count}")
    print(f"   • Static candidates     : {len(grouped_asset_ids['static'])}")
    print(f"   • Review candidates     : {len(grouped_asset_ids['review'])}")
    if include_dynamic:
        print(f"   • Dynamic candidates    : {len(grouped_asset_ids['dynamic'])}")
    print()

    tag_name_map = {
        "static": os.environ.get("TAG_STATIC", "video:static"),
        "review": os.environ.get("TAG_REVIEW", "video:review"),
        "dynamic": os.environ.get("TAG_DYNAMIC", "video:dynamic"),
    }

    album_name_map = {
        "static": "[Static] Videos",
        "review": "[Review] Videos",
        "dynamic": "[Dynamic] Videos",
    }

    # 3. Apply Tags to Assets
    if sync_tags:
        print("🏷  Syncing Immich Tags...")
        existing_tags = client.get_tags()
        tags_by_name = {t.get("name"): t for t in existing_tags}

        for decision, asset_ids in grouped_asset_ids.items():
            if not asset_ids:
                continue
            target_tag_name = tag_name_map[decision]

            tag = tags_by_name.get(target_tag_name)
            if not tag:
                if dry_run:
                    print(f"   🔍 [DRY-RUN] Would create Tag '{target_tag_name}'")
                    tag_id = "dry-run-tag-id"
                else:
                    print(f"   🏷  Creating Tag '{target_tag_name}'...")
                    tag = client.create_tag(target_tag_name)
                    tag_id = tag["id"]
            else:
                tag_id = tag["id"]

            if dry_run:
                print(f"   🔍 [DRY-RUN] Would apply tag '{target_tag_name}' to {len(asset_ids)} assets")
            else:
                print(f"   🏷  Applying tag '{target_tag_name}' to {len(asset_ids)} assets...")
                client.tag_assets(tag_id, asset_ids)
                print(f"   ✅ Tagged '{target_tag_name}' ({len(asset_ids)} assets)")
        print()

    # 4. Populate Albums
    if sync_albums:
        print("📁 Syncing Immich Albums...")
        existing_albums = client.get_albums()
        albums_by_name = {a.get("albumName"): a for a in existing_albums}

        for decision, asset_ids in grouped_asset_ids.items():
            if not asset_ids:
                continue
            target_album_name = album_name_map[decision]

            album = albums_by_name.get(target_album_name)
            if not album:
                if dry_run:
                    print(f"   🔍 [DRY-RUN] Would create Album '{target_album_name}'")
                    album_id = "dry-run-album-id"
                    existing_in_album = set()
                else:
                    print(f"   📁 Creating Album '{target_album_name}'...")
                    album = client.create_album(target_album_name)
                    album_id = album["id"]
                    existing_in_album = set()
            else:
                album_id = album["id"]
                existing_in_album = client.get_album_assets(album_id) if not dry_run else set()

            to_add = [aid for aid in asset_ids if aid not in existing_in_album]

            print(f"   📦 Album '{target_album_name}':")
            print(f"      • Total classified : {len(asset_ids)}")
            print(f"      • Already in album : {len(existing_in_album)}")
            print(f"      • New to add       : {len(to_add)}")

            if to_add:
                if dry_run:
                    print(f"      🔍 [DRY-RUN] Would add {len(to_add)} assets to '{target_album_name}'")
                else:
                    print(f"      🚀 Adding {len(to_add)} assets to '{target_album_name}'...")
                    client.add_assets_to_album(album_id, to_add)
                    print(f"      ✅ Done.")
        print()


# ─────────────────────────────────────────────
# RESTORE CHECKPOINT DECISIONS FROM MOTION SCORES
# ─────────────────────────────────────────────

def restore_checkpoint_decisions(ckpt: Checkpoint, sensitivity: str = "medium") -> int:
    """
    Restores the original video classifications (static, review, dynamic) in the SQLite
    checkpoint database from the recorded motion scores without needing to re-scan videos.
    """
    from core import SENSITIVITY_PRESETS
    thresholds = SENSITIVITY_PRESETS.get(sensitivity, SENSITIVITY_PRESETS["medium"])
    static_max_m = thresholds["static_max_motion"]
    static_max_z = thresholds["static_max_active_zones"]
    review_max_m = thresholds["review_max_motion"]
    review_max_z = thresholds["review_max_active_zones"]

    rows = ckpt.all_rows()
    restored_counts = {"static": 0, "review": 0, "dynamic": 0}

    for r in rows:
        g_str = r.get("global_motion_score")
        z_str = r.get("active_zone_ratio")
        if not g_str or not z_str:
            continue
        try:
            global_motion = float(g_str)
            active_ratio = float(z_str)
        except (ValueError, TypeError):
            continue

        if global_motion <= static_max_m and active_ratio <= static_max_z:
            new_dec = "static"
        elif global_motion <= review_max_m or active_ratio <= review_max_z:
            new_dec = "review"
        else:
            new_dec = "dynamic"

        aid = r.get("asset_id")
        fn = r.get("filename")
        ckpt.update_decision(aid or fn, new_dec)
        restored_counts[new_dec] += 1

    print("🔄 Restored Checkpoint Classifications from Raw Motion Scores:")
    print(f"   • Static  : {restored_counts['static']}")
    print(f"   • Review  : {restored_counts['review']}")
    print(f"   • Dynamic : {restored_counts['dynamic']}")
    print()
    return sum(restored_counts.values())


# ─────────────────────────────────────────────
# PULL ALBUMS TO CHECKPOINT DB
# ─────────────────────────────────────────────

def pull_albums_to_checkpoint(
    client: ImmichClient,
    ckpt: Checkpoint,
    dry_run: bool = False,
    sync_tags: bool = True,
):
    """
    Pulls classification changes from Immich albums back into local SQLite database.
    If a video was removed from '[Static] Videos' or placed into '[Dynamic] Videos',
    its SQLite decision is updated accordingly.
    """
    print("📥 Pulling album state from Immich into local SQLite database...")
    albums = client.get_albums()
    albums_by_name = {a.get("albumName"): a for a in albums}

    static_name = os.environ.get("ALBUM_STATIC", "[Static] Videos")
    review_name = os.environ.get("ALBUM_REVIEW", "[Review] Videos")
    dynamic_name = os.environ.get("ALBUM_DYNAMIC", "[Dynamic] Videos")

    static_album = albums_by_name.get(static_name)
    review_album = albums_by_name.get(review_name)
    dynamic_album = albums_by_name.get(dynamic_name)

    if not static_album and not review_album and not dynamic_album:
        print(f"❌ Error: None of the classification albums ('{static_name}', '{review_name}', '{dynamic_name}') exist in Immich.")
        print("   Did you run `python immich_sync.py` to push classifications and create the albums first?")
        print("   Aborting pull to protect local database.")
        return

    static_ids = client.get_album_assets(static_album["id"]) if static_album else set()
    review_ids = client.get_album_assets(review_album["id"]) if review_album else set()
    dynamic_ids = client.get_album_assets(dynamic_album["id"]) if dynamic_album else set()

    total_album_assets = len(static_ids) + len(review_ids) + len(dynamic_ids)
    print(f"   • Album '{static_name}': {len(static_ids)} assets")
    print(f"   • Album '{review_name}': {len(review_ids)} assets")
    print(f"   • Album '{dynamic_name}': {len(dynamic_ids)} assets")
    print()

    if total_album_assets == 0:
        print("⚠️  Warning: The albums in Immich currently contain 0 assets.")
        print("   Did you populate the albums first using `python immich_sync.py`?")
        print("   Aborting pull to avoid accidentally clearing local classifications.")
        return

    all_rows = ckpt.all_rows()
    if not all_rows:
        print("⚠️  Checkpoint database is empty. No local records to update.")
        return

    changes: Dict[str, List[Tuple[str, str, str]]] = {
        "static_to_dynamic": [],
        "static_to_review": [],
        "review_to_static": [],
        "review_to_dynamic": [],
        "dynamic_to_static": [],
        "dynamic_to_review": [],
    }

    updated_count = 0

    for r in all_rows:
        aid = r.get("asset_id")
        old_decision = r.get("decision", "")
        if not aid:
            continue

        target_decision = None
        if aid in static_ids:
            target_decision = "static"
        elif aid in review_ids:
            target_decision = "review"
        elif aid in dynamic_ids:
            target_decision = "dynamic"
        elif old_decision == "static" and static_album and len(static_ids) > 0 and aid not in static_ids:
            # Video was previously marked static, but user explicitly removed it from the static album in Immich UI
            target_decision = "dynamic"

        if target_decision and target_decision != old_decision:
            change_key = f"{old_decision}_to_{target_decision}"
            fname = r.get("original_file_name") or Path(r.get("filename", "")).name
            if change_key in changes:
                changes[change_key].append((aid, fname, target_decision))
            else:
                changes.setdefault(change_key, []).append((aid, fname, target_decision))

            if not dry_run:
                ckpt.update_decision(aid, target_decision)
            updated_count += 1

    print("🔄 Synchronization Summary:")
    has_any_change = False
    for change_key, items in changes.items():
        if items:
            has_any_change = True
            parts = change_key.split("_to_")
            from_dec, to_dec = parts[0], parts[1]
            print(f"   • Reclassified {len(items):>3} videos: [{from_dec.upper()}] ➔ [{to_dec.upper()}]")
            for aid, fname, _ in items[:5]:
                print(f"       - {fname} ({aid[:8]}...)")
            if len(items) > 5:
                print(f"       ... and {len(items) - 5} more")

    if not has_any_change:
        print("   ✅ Local checkpoint is already 100% in sync with Immich albums. No changes needed.")
    else:
        status_msg = "Would update" if dry_run else "Successfully updated"
        print(f"\n   🎉 {status_msg} {updated_count} record(s) in SQLite checkpoint.")

    # Optionally re-sync tags in Immich if user updated albums
    if sync_tags and updated_count > 0 and not dry_run:
        print("\n🏷  Updating Immich tags to match new album classifications...")
        existing_tags = client.get_tags()
        tags_by_name = {t.get("name"): t for t in existing_tags}
        tag_name_map = {
            "static": os.environ.get("TAG_STATIC", "video:static"),
            "review": os.environ.get("TAG_REVIEW", "video:review"),
            "dynamic": os.environ.get("TAG_DYNAMIC", "video:dynamic"),
        }
        for change_key, items in changes.items():
            if not items:
                continue
            parts = change_key.split("_to_")
            from_dec, to_dec = parts[0], parts[1]
            old_tag_name = tag_name_map.get(from_dec)
            new_tag_name = tag_name_map.get(to_dec)
            old_tag_obj = tags_by_name.get(old_tag_name)
            new_tag_obj = tags_by_name.get(new_tag_name)
            aids = [item[0] for item in items]
            if old_tag_obj:
                client.untag_assets(old_tag_obj["id"], aids)
            if not new_tag_obj and new_tag_name:
                new_tag_obj = client.create_tag(new_tag_name)
                tags_by_name[new_tag_name] = new_tag_obj
            if new_tag_obj:
                client.tag_assets(new_tag_obj["id"], aids)
        print("   ✅ Immich tags updated.")
    print()


# ─────────────────────────────────────────────
# STORAGE METRICS & BREAKDOWN
# ─────────────────────────────────────────────

def format_duration(seconds: float) -> str:
    """Formats seconds into human-readable duration."""
    if seconds <= 0:
        return "0s"
    s = int(seconds)
    hours = s // 3600
    minutes = (s % 3600) // 60
    secs = s % 60
    if hours > 0:
        return f"{hours}h {minutes}m {secs}s"
    if minutes > 0:
        return f"{minutes}m {secs}s"
    return f"{secs}s"


def display_storage_stats(
    client: Optional[ImmichClient],
    ckpt: Checkpoint,
):
    """
    Calculates and displays a storage breakdown and estimated savings across video albums.
    """
    print("📊 Calculating video storage and duration metrics...")
    all_rows = ckpt.all_rows()

    immich_videos_map = {}
    if client:
        try:
            v_list = client.get_all_video_assets()
            immich_videos_map = {a["id"]: a for a in v_list if "id" in a}
        except Exception:
            pass

    stats: Dict[str, Dict[str, Any]] = {
        "static": {"count": 0, "size_bytes": 0, "duration_s": 0.0},
        "review": {"count": 0, "size_bytes": 0, "duration_s": 0.0},
        "dynamic": {"count": 0, "size_bytes": 0, "duration_s": 0.0},
        "other": {"count": 0, "size_bytes": 0, "duration_s": 0.0},
    }

    for r in all_rows:
        dec = r.get("decision", "other")
        if dec not in stats:
            dec = "other"

        size_bytes = 0
        fn = r.get("filename")
        if fn:
            p = Path(fn)
            if p.is_file():
                try:
                    size_bytes = p.stat().st_size
                except Exception:
                    pass

        if size_bytes == 0:
            aid = r.get("asset_id")
            if aid and aid in immich_videos_map:
                asset_obj = immich_videos_map[aid]
                exif = asset_obj.get("exifInfo") or {}
                size_bytes = int(exif.get("fileSizeInByte") or asset_obj.get("size") or 0)

        dur_s = 0.0
        try:
            dur_s = float(r.get("duration_s") or 0.0)
        except (ValueError, TypeError):
            pass
        if dur_s == 0.0:
            aid = r.get("asset_id")
            if aid and aid in immich_videos_map:
                dur_s = float(immich_videos_map[aid].get("duration") or 0.0)

        stats[dec]["count"] += 1
        stats[dec]["size_bytes"] += size_bytes
        stats[dec]["duration_s"] += dur_s

    total_count = sum(s["count"] for s in stats.values())
    total_size = sum(s["size_bytes"] for s in stats.values())
    total_dur = sum(s["duration_s"] for s in stats.values())

    static_size = stats["static"]["size_bytes"]
    static_count = stats["static"]["count"]
    # Estimate frame extraction size (~350 KB per photo)
    estimated_frame_size = static_count * 350 * 1024
    potential_savings_bytes = max(0, static_size - estimated_frame_size)
    potential_savings_pct = (potential_savings_bytes / static_size * 100) if static_size > 0 else 0.0

    print("\n" + "═" * 72)
    print("               📦 IMMICH VIDEO STORAGE & ALBUM BREAKDOWN")
    print("═" * 72)
    print(f" {'Category / Album':<22} | {'Count':<8} | {'Total Duration':<16} | {'Storage Space':<15}")
    print("─" * 72)

    categories = [
        ("static", "📁 [Static] Videos"),
        ("review", "📁 [Review] Videos"),
        ("dynamic", "📁 [Dynamic] Videos"),
    ]
    if stats["other"]["count"] > 0:
        categories.append(("other", "❓ Other / Errors"))

    for key, label in categories:
        c = stats[key]["count"]
        d = format_duration(stats[key]["duration_s"])
        s = format_bytes(stats[key]["size_bytes"])
        print(f" {label:<22} | {c:<8} | {d:<16} | {s:<15}")

    print("─" * 72)
    print(f" {'TOTAL':<22} | {total_count:<8} | {format_duration(total_dur):<16} | {format_bytes(total_size):<15}")
    print("═" * 72)

    if static_count > 0 and static_size > 0:
        print("\n💡 Storage Optimization Potential:")
        print(f"   • Static videos storage       : {format_bytes(static_size)} ({static_count} videos)")
        print(f"   • Extracted still frames size : ~{format_bytes(estimated_frame_size)}")
        print(f"   • Estimated space savings     : {format_bytes(potential_savings_bytes)} ({potential_savings_pct:.1f}% reduction)")
    print()


# ─────────────────────────────────────────────
# CLI ENTRYPOINT
# ─────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Sync classified videos between checkpoint DB and Immich Tags / Albums.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--api-url", default=os.environ.get("IMMICH_API_URL"),
                   help="Immich API URL (or set IMMICH_API_URL in .env)")
    p.add_argument("--api-key", default=os.environ.get("IMMICH_API_KEY"),
                   help="Immich API Key (or set IMMICH_API_KEY in .env)")
    p.add_argument("--db", "--db-path", dest="db_path",
                   default=os.environ.get("DB_PATH", "./detection_checkpoint.sqlite"),
                   help="Path to SQLite checkpoint database (default: ./detection_checkpoint.sqlite)")
    p.add_argument("--pull-albums", "--pull", action="store_true",
                   help="Pull classifications from Immich albums back into local SQLite checkpoint DB")
    p.add_argument("--restore", "--recalculate", action="store_true",
                   help="Restore / recalculate classifications in SQLite checkpoint from raw motion scores")
    p.add_argument("--sensitivity", default=os.environ.get("SENSITIVITY", "medium"),
                   choices=["low", "medium", "high"],
                   help="Sensitivity preset to use when recalculating / restoring (default: medium)")
    p.add_argument("--stats", "--storage", action="store_true",
                   help="Display video count, total duration, and storage space breakdown for all albums")
    p.add_argument("--no-tags", action="store_true",
                   help="Skip applying tags to assets")
    p.add_argument("--no-albums", action="store_true",
                   help="Skip adding assets to albums")
    p.add_argument("--no-tag-sync-on-pull", action="store_true",
                   help="Skip updating Immich tags when pulling album changes")
    p.add_argument("--include-dynamic", action="store_true", default=True,
                   help="Also tag and create album for dynamic videos (default: True)")
    p.add_argument("--upload-extracted", action="store_true",
                   help="Also upload any local extracted frames in EXTRACT_OUTPUT_DIR to Immich")
    p.add_argument("--dry-run", action="store_true",
                   help="Preview operations without modifying Immich or SQLite")
    return p.parse_args()


def main():
    args = parse_args()

    db_path = Path(args.db_path).resolve()
    if not db_path.exists():
        print(f"❌ Error: Checkpoint database not found at {db_path}")
        print("   Run `python detect.py` first to analyze your video library.")
        sys.exit(1)

    ckpt = Checkpoint(db_path)

    # Mode 0: Restore / Recalculate Classifications from Motion Scores
    if args.restore:
        restore_checkpoint_decisions(ckpt, sensitivity=args.sensitivity)
        display_storage_stats(client=None, ckpt=ckpt)
        return

    # If only --stats is requested and API credentials aren't provided, we can still show stats from DB
    client = None
    if args.api_url and args.api_key:
        client = ImmichClient(args.api_url, args.api_key)
        try:
            ver = client.ping()
            print(f"🌐 Connected to Immich Server (Version: {ver.get('major', '')}.{ver.get('minor', '')}.{ver.get('patch', '')})")
        except Exception as e:
            if not (args.stats and not args.pull_albums):
                print(f"❌ Failed to connect to Immich server at {args.api_url}: {e}")
                sys.exit(1)
            else:
                print(f"⚠️  Immich server connection failed ({e}), proceeding with local checkpoint metadata only.")
                client = None
    elif not args.stats:
        print("❌ Error: Missing Immich API configuration.")
        print("   Provide --api-url and --api-key or set IMMICH_API_URL and IMMICH_API_KEY in .env")
        sys.exit(1)

    if args.dry_run:
        print("🔎 Running in DRY-RUN mode. No write changes will be made.\n")

    # Mode 1: Pull album state from Immich to SQLite DB
    if args.pull_albums:
        if not client:
            print("❌ Error: Immich API credentials required for --pull-albums.")
            sys.exit(1)
        pull_albums_to_checkpoint(
            client=client,
            ckpt=ckpt,
            dry_run=args.dry_run,
            sync_tags=not args.no_tag_sync_on_pull,
        )

    # Mode 2: Show Storage Stats
    if args.stats:
        display_storage_stats(client=client, ckpt=ckpt)

    # Mode 3: Push Sync (default if neither --pull-albums nor --stats was explicitly given, or if requested)
    if not args.pull_albums and not args.stats:
        if not client:
            print("❌ Error: Immich API credentials required for sync.")
            sys.exit(1)
        sync_immich(
            client=client,
            ckpt=ckpt,
            dry_run=args.dry_run,
            sync_tags=not args.no_tags,
            sync_albums=not args.no_albums,
            include_dynamic=args.include_dynamic,
        )
        display_storage_stats(client=client, ckpt=ckpt)

    # Optional Upload of Extracted Frames
    if args.upload_extracted and client:
        ext_dir = Path(os.environ.get("EXTRACT_OUTPUT_DIR", "./extracted_frames")).resolve()
        if not ext_dir.exists():
            print(f"⚠️  Extracted frames directory not found: {ext_dir}")
        else:
            images = sorted([p for p in ext_dir.iterdir() if p.is_file() and p.suffix.lower() in (".jpg", ".jpeg", ".png")])
            if not images:
                print(f"⚠️  No images found in {ext_dir} to upload.")
            else:
                tag_name = os.environ.get("TAG_EXTRACTED", "video:extracted")
                if args.dry_run:
                    print(f"🔍 [DRY-RUN] Would upload {len(images)} frames from {ext_dir} and tag as '{tag_name}'")
                else:
                    print(f"☁️  Uploading {len(images)} extracted frames to Immich...")
                    tags = client.get_tags()
                    extracted_tag = next((t for t in tags if t.get("name") == tag_name), None)
                    if not extracted_tag:
                        extracted_tag = client.create_tag(tag_name)
                    tag_id = extracted_tag["id"]

                    uploaded_ids = []
                    for img_path in images:
                        res = client.upload_asset(img_path, created_at=img_path.stat().st_mtime)
                        if res and "id" in res:
                            aid = res["id"]
                            status_str = res.get("status", "created")
                            uploaded_ids.append(aid)
                            print(f"   Uploaded: {img_path.name} -> Immich ID: {aid} ({status_str})")
                        else:
                            print(f"   Uploaded: {img_path.name} -> (Response: {res})")

                    if uploaded_ids:
                        client.tag_assets(tag_id, uploaded_ids)
                        print(f"✅ Uploaded and tagged with '{tag_name}' ({len(uploaded_ids)} items)")

                        # Also add to '[Extracted] Photos' album for instant visibility in Immich UI
                        album_name = "[Extracted] Photos"
                        albums = client.get_albums()
                        target_album = next((a for a in albums if a.get("albumName") == album_name), None)
                        if not target_album:
                            target_album = client.create_album(album_name)
                        album_id = target_album["id"]
                        client.add_assets_to_album(album_id, uploaded_ids)
                        print(f"📁 Added {len(uploaded_ids)} images to Album '{album_name}'")

                        # Ensure all assets in the extracted album have the tag applied
                        album_asset_ids = client.get_album_assets(album_id)
                        all_to_tag = list(set(uploaded_ids) | album_asset_ids)
                        client.tag_assets(tag_id, all_to_tag)
                        print(f"🏷  Verified tag '{tag_name}' across all {len(all_to_tag)} assets in '{album_name}'")

    print("✨ Complete!")


if __name__ == "__main__":
    main()
