#!/usr/bin/env python3
"""
immich_sync.py — Sync classified videos to Immich Tags and Albums.

Features:
- Queries Immich REST API for asset catalog.
- Maps local disk paths / filenames to Immich Asset IDs.
- Tags every video with its classification:
    • Tag: "video:static"
    • Tag: "video:review"
    • Tag: "video:dynamic"
- Populates corresponding Immich Albums:
    • [Static] Videos
    • [Review] Videos
    • [Dynamic] Videos
- Supports tagging extracted images with "video:extracted".
- Supports --dry-run to preview actions safely before modifying Immich.

Usage:
    python immich_sync.py [options]

Options:
    --api-url URL        Immich URL (or set IMMICH_API_URL in .env)
    --api-key KEY        Immich API Key (or set IMMICH_API_KEY in .env)
    --db PATH            Path to SQLite checkpoint (default: ./detection_checkpoint.sqlite)
    --no-tags            Skip adding tags to assets
    --no-albums          Skip adding assets to albums
    --include-dynamic    Also tag and create album for dynamic videos
    --dry-run            Preview tag and album operations without modifying Immich
"""

import argparse
import json
import os
import sys
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any, Dict, List, Optional, Set

from core import Checkpoint

# ─────────────────────────────────────────────
# IMMICH API CLIENT
# ─────────────────────────────────────────────

class ImmichClient:
    def __init__(self, base_url: str, api_key: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.headers = {
            "x-api-key": self.api_key,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def _request(self, method: str, endpoint: str, data: Optional[dict] = None) -> Any:
        url = f"{self.base_url}{endpoint}"
        body = json.dumps(data).encode("utf-8") if data is not None else None
        req = urllib.request.Request(url, data=body, headers=self.headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                resp_text = resp.read().decode("utf-8")
                return json.loads(resp_text) if resp_text else None
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8")
            raise RuntimeError(f"Immich API HTTP {e.code} ({e.reason}) on {method} {endpoint}: {err_body}")
        except Exception as e:
            raise RuntimeError(f"Immich API request failed ({method} {endpoint}): {e}")

    def ping(self) -> dict:
        """Verifies server connectivity and authentication."""
        return self._request("GET", "/api/server/version")

    def get_all_video_assets(self) -> List[Dict[str, Any]]:
        """Retrieves all video assets from Immich library."""
        videos = []
        page = 1
        page_size = 1000

        print("📡 Fetching video catalog from Immich API...")
        while True:
            payload = {
                "type": "VIDEO",
                "size": page_size,
                "page": page,
                "withExif": True,
                "isVisible": True,
            }
            res = self._request("POST", "/api/search/metadata", payload)
            assets = res.get("assets", {}).get("items", []) if isinstance(res, dict) else []
            if not assets:
                break
            videos.extend(assets)
            if len(assets) < page_size:
                break
            page += 1
            print(f"   Fetched {len(videos)} videos so far (page {page})...")

        print(f"✅ Found {len(videos)} total video assets in Immich.")
        return videos

    # ─────────────────────────────────────────────
    # ALBUMS API
    # ─────────────────────────────────────────────

    def get_albums(self) -> List[Dict[str, Any]]:
        """Retrieves existing albums."""
        return self._request("GET", "/api/albums") or []

    def create_album(self, album_name: str) -> Dict[str, Any]:
        """Creates a new album."""
        return self._request("POST", "/api/albums", {"albumName": album_name, "description": "Auto-generated by immich-static"})

    def get_album_assets(self, album_id: str) -> Set[str]:
        """Gets all asset IDs currently in an album."""
        album = self._request("GET", f"/api/albums/{album_id}") or {}
        assets = album.get("assets", [])
        return {a["id"] for a in assets if "id" in a}

    def add_assets_to_album(self, album_id: str, asset_ids: List[str]) -> Any:
        """Adds asset IDs to an album in batches of 500."""
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            self._request("PUT", f"/api/albums/{album_id}/assets", {"ids": batch})

    # ─────────────────────────────────────────────
    # TAGS API
    # ─────────────────────────────────────────────

    def get_tags(self) -> List[Dict[str, Any]]:
        """Retrieves all tags."""
        try:
            return self._request("GET", "/api/tags") or []
        except Exception:
            return []

    def create_tag(self, tag_name: str) -> Dict[str, Any]:
        """Creates a new tag."""
        try:
            return self._request("POST", "/api/tags", {"name": tag_name, "type": "CUSTOM"})
        except Exception:
            # Fallback for older versions
            return self._request("POST", "/api/tags", {"name": tag_name})

    def tag_assets(self, tag_id: str, asset_ids: List[str]) -> Any:
        """Tags asset IDs in batches of 500 with response verification and retries."""
        import time
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            res = None
            try:
                res = self._request("PUT", f"/api/tags/{tag_id}/assets", {"ids": batch})
            except Exception:
                try:
                    res = self._request("POST", f"/api/tags/{tag_id}/assets", {"ids": batch})
                except Exception as e:
                    print(f"⚠️  Tag request error: {e}")

            # Check for any items that failed
            if isinstance(res, list):
                failed = [
                    item.get("id") for item in res
                    if isinstance(item, dict) and not item.get("success", True) and item.get("id")
                ]
                if failed:
                    time.sleep(1.0)
                    try:
                        self._request("PUT", f"/api/tags/{tag_id}/assets", {"ids": failed})
                    except Exception:
                        pass
        return res

    def upload_asset(self, file_path: Path, created_at: Optional[str] = None) -> Optional[Dict[str, Any]]:
        """Uploads a still frame image to Immich."""
        import mimetypes
        import uuid
        from datetime import datetime, timezone

        boundary = f"----WebKitFormBoundary{uuid.uuid4().hex}"
        filename = file_path.name
        mime_type = mimetypes.guess_type(str(file_path))[0] or "image/jpeg"
        with open(file_path, "rb") as f:
            file_data = f.read()

        # Format ISO8601 UTC timestamp with Z
        if created_at:
            try:
                # If already string, try parsing or ensure ends with Z
                if isinstance(created_at, (int, float)):
                    dt = datetime.fromtimestamp(created_at, tz=timezone.utc)
                    utc_time_str = dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
                else:
                    dt = datetime.fromisoformat(created_at.replace("Z", "+00:00")).astimezone(timezone.utc)
                    utc_time_str = dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
            except Exception:
                utc_time_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
        else:
            utc_time_str = datetime.fromtimestamp(file_path.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

        device_asset_id = f"{file_path.stem}-{uuid.uuid4().hex[:8]}"

        parts = []
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"deviceAssetId\"\r\n\r\n{device_asset_id}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"deviceId\"\r\n\r\nimmich-static\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileCreatedAt\"\r\n\r\n{utc_time_str}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileModifiedAt\"\r\n\r\n{utc_time_str}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"isFavorite\"\r\n\r\nfalse\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"assetData\"; filename=\"{filename}\"\r\nContent-Type: {mime_type}\r\n\r\n".encode("utf-8"))
        parts.append(file_data)
        parts.append(f"\r\n--{boundary}--\r\n".encode("utf-8"))

        body = b"".join(parts)
        headers = {
            "x-api-key": self.api_key,
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "Accept": "application/json",
        }
        url = f"{self.base_url}/api/assets"
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                res_text = resp.read().decode("utf-8")
                return json.loads(res_text) if res_text else None
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8")
            raise RuntimeError(f"Immich upload failed ({e.code} {e.reason}): {err_msg}")
        except Exception as e:
            raise RuntimeError(f"Immich upload request failed: {e}")


# ─────────────────────────────────────────────
# SYNC LOGIC (TAGS & ALBUMS)
# ─────────────────────────────────────────────

def sync_immich(
    client: ImmichClient,
    ckpt: Checkpoint,
    dry_run: bool = False,
    sync_tags: bool = True,
    sync_albums: bool = True,
    include_dynamic: bool = False
):
    # 1. Fetch Immich Assets & Build Lookup Maps
    immich_videos = client.get_all_video_assets()

    path_to_asset: Dict[str, Dict[str, Any]] = {}
    name_to_assets: Dict[str, List[Dict[str, Any]]] = {}

    for asset in immich_videos:
        aid = asset.get("id")
        orig_path = asset.get("originalPath") or ""
        orig_name = asset.get("originalFileName") or Path(orig_path).name

        if orig_path:
            norm_path = os.path.normpath(orig_path)
            path_to_asset[norm_path] = asset
            path_to_asset[Path(orig_path).name] = asset

        if orig_name:
            name_to_assets.setdefault(orig_name, []).append(asset)

    # 2. Match Checkpoint Entries
    all_rows = ckpt.all_rows()
    print(f"📊 Checkpoint contains {len(all_rows)} classified files.")

    grouped_asset_ids: Dict[str, List[str]] = {
        "static": [],
        "review": [],
        "dynamic": [],
    }

    matched_count = 0
    unmatched_count = 0

    for r in all_rows:
        decision = r.get("decision")
        if decision not in ("static", "review", "dynamic"):
            continue
        if decision == "dynamic" and not include_dynamic:
            continue

        aid = r.get("asset_id")
        if aid and aid in {a["id"] for a in immich_videos}:
            grouped_asset_ids[decision].append(aid)
            matched_count += 1
            continue

        filename_str = r.get("filename", "")
        file_path = Path(filename_str)
        file_name = file_path.name
        matched_asset = None

        norm_full = os.path.normpath(filename_str)
        if norm_full in path_to_asset:
            matched_asset = path_to_asset[norm_full]
        elif file_name in name_to_assets and len(name_to_assets[file_name]) == 1:
            matched_asset = name_to_assets[file_name][0]
        else:
            for p, a in path_to_asset.items():
                if filename_str.endswith(p) or p.endswith(str(file_path.name)):
                    matched_asset = a
                    break

        if matched_asset:
            aid = matched_asset["id"]
            grouped_asset_ids[decision].append(aid)
            matched_count += 1
            if not r.get("asset_id"):
                r["asset_id"] = aid
                ckpt.record(aid, r)
        else:
            unmatched_count += 1

    print(f"🔗 Match Results:")
    print(f"   • Matched Immich Assets : {matched_count}")
    print(f"   • Unmatched Local Files : {unmatched_count}")
    print(f"   • Static candidates     : {len(grouped_asset_ids['static'])}")
    print(f"   • Review candidates     : {len(grouped_asset_ids['review'])}")
    if include_dynamic:
        print(f"   • Dynamic candidates    : {len(grouped_asset_ids['dynamic'])}")
    print()

    tag_name_map = {
        "static": os.environ.get("TAG_STATIC", "video:static"),
        "review": os.environ.get("TAG_REVIEW", "video:review"),
        "dynamic": os.environ.get("TAG_DYNAMIC", "video:dynamic"),
    }

    album_name_map = {
        "static": "[Static] Videos",
        "review": "[Review] Videos",
        "dynamic": "[Dynamic] Videos",
    }

    # 3. Apply Tags to Assets
    if sync_tags:
        print("🏷  Syncing Immich Tags...")
        existing_tags = client.get_tags()
        tags_by_name = {t.get("name"): t for t in existing_tags}

        for decision, asset_ids in grouped_asset_ids.items():
            if not asset_ids:
                continue
            target_tag_name = tag_name_map[decision]

            tag = tags_by_name.get(target_tag_name)
            if not tag:
                if dry_run:
                    print(f"   🔍 [DRY-RUN] Would create Tag '{target_tag_name}'")
                    tag_id = "dry-run-tag-id"
                else:
                    print(f"   🏷  Creating Tag '{target_tag_name}'...")
                    tag = client.create_tag(target_tag_name)
                    tag_id = tag["id"]
            else:
                tag_id = tag["id"]

            if dry_run:
                print(f"   🔍 [DRY-RUN] Would apply tag '{target_tag_name}' to {len(asset_ids)} assets")
            else:
                print(f"   🏷  Applying tag '{target_tag_name}' to {len(asset_ids)} assets...")
                client.tag_assets(tag_id, asset_ids)
                print(f"   ✅ Tagged '{target_tag_name}' ({len(asset_ids)} assets)")
        print()

    # 4. Populate Albums
    if sync_albums:
        print("📁 Syncing Immich Albums...")
        existing_albums = client.get_albums()
        albums_by_name = {a.get("albumName"): a for a in existing_albums}

        for decision, asset_ids in grouped_asset_ids.items():
            if not asset_ids:
                continue
            target_album_name = album_name_map[decision]

            album = albums_by_name.get(target_album_name)
            if not album:
                if dry_run:
                    print(f"   🔍 [DRY-RUN] Would create Album '{target_album_name}'")
                    album_id = "dry-run-album-id"
                    existing_in_album = set()
                else:
                    print(f"   📁 Creating Album '{target_album_name}'...")
                    album = client.create_album(target_album_name)
                    album_id = album["id"]
                    existing_in_album = set()
            else:
                album_id = album["id"]
                existing_in_album = client.get_album_assets(album_id) if not dry_run else set()

            to_add = [aid for aid in asset_ids if aid not in existing_in_album]

            print(f"   📦 Album '{target_album_name}':")
            print(f"      • Total classified : {len(asset_ids)}")
            print(f"      • Already in album : {len(existing_in_album)}")
            print(f"      • New to add       : {len(to_add)}")

            if to_add:
                if dry_run:
                    print(f"      🔍 [DRY-RUN] Would add {len(to_add)} assets to '{target_album_name}'")
                else:
                    print(f"      🚀 Adding {len(to_add)} assets to '{target_album_name}'...")
                    client.add_assets_to_album(album_id, to_add)
                    print(f"      ✅ Done.")
        print()


# ─────────────────────────────────────────────
# CLI ENTRYPOINT
# ─────────────────────────────────────────────

def parse_args():
    p = argparse.ArgumentParser(
        description="Sync classified videos from checkpoint DB to Immich Tags and Albums.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    p.add_argument("--api-url", default=os.environ.get("IMMICH_API_URL"),
                   help="Immich API URL (or set IMMICH_API_URL in .env)")
    p.add_argument("--api-key", default=os.environ.get("IMMICH_API_KEY"),
                   help="Immich API Key (or set IMMICH_API_KEY in .env)")
    p.add_argument("--db", "--db-path", dest="db_path",
                   default=os.environ.get("DB_PATH", "./detection_checkpoint.sqlite"),
                   help="Path to SQLite checkpoint database (default: ./detection_checkpoint.sqlite)")
    p.add_argument("--no-tags", action="store_true",
                   help="Skip applying tags to assets")
    p.add_argument("--no-albums", action="store_true",
                   help="Skip adding assets to albums")
    p.add_argument("--include-dynamic", action="store_true", default=True,
                   help="Also tag and create album for dynamic videos (default: True)")
    p.add_argument("--upload-extracted", action="store_true",
                   help="Also upload any local extracted frames in EXTRACT_OUTPUT_DIR to Immich")
    p.add_argument("--dry-run", action="store_true",
                   help="Preview tag and album operations without modifying Immich")
    return p.parse_args()


def main():
    args = parse_args()

    if not args.api_url or not args.api_key:
        print("❌ Error: Missing Immich API configuration.")
        print("   Provide --api-url and --api-key or set IMMICH_API_URL and IMMICH_API_KEY in .env")
        sys.exit(1)

    db_path = Path(args.db_path).resolve()
    if not db_path.exists():
        print(f"❌ Error: Checkpoint database not found at {db_path}")
        print("   Run `python detect.py` first to analyze your video library.")
        sys.exit(1)

    ckpt = Checkpoint(db_path)
    client = ImmichClient(args.api_url, args.api_key)

    try:
        ver = client.ping()
        print(f"🌐 Connected to Immich Server (Version: {ver.get('major', '')}.{ver.get('minor', '')}.{ver.get('patch', '')})")
    except Exception as e:
        print(f"❌ Failed to connect to Immich server at {args.api_url}: {e}")
        sys.exit(1)

    if args.dry_run:
        print("🔎 Running in DRY-RUN mode. No changes will be made to Immich.\n")

    sync_immich(
        client=client,
        ckpt=ckpt,
        dry_run=args.dry_run,
        sync_tags=not args.no_tags,
        sync_albums=not args.no_albums,
        include_dynamic=args.include_dynamic,
    )

    # Optional Upload of Extracted Frames
    if args.upload_extracted:
        ext_dir = Path(os.environ.get("EXTRACT_OUTPUT_DIR", "./extracted_frames")).resolve()
        if not ext_dir.exists():
            print(f"⚠️  Extracted frames directory not found: {ext_dir}")
        else:
            images = sorted([p for p in ext_dir.iterdir() if p.is_file() and p.suffix.lower() in (".jpg", ".jpeg", ".png")])
            if not images:
                print(f"⚠️  No images found in {ext_dir} to upload.")
            else:
                tag_name = os.environ.get("TAG_EXTRACTED", "video:extracted")
                if args.dry_run:
                    print(f"🔍 [DRY-RUN] Would upload {len(images)} frames from {ext_dir} and tag as '{tag_name}'")
                else:
                    from datetime import datetime
                    print(f"☁️  Uploading {len(images)} extracted frames to Immich...")
                    tags = client.get_tags()
                    extracted_tag = next((t for t in tags if t.get("name") == tag_name), None)
                    if not extracted_tag:
                        extracted_tag = client.create_tag(tag_name)
                    tag_id = extracted_tag["id"]

                    uploaded_ids = []
                    for img_path in images:
                        res = client.upload_asset(img_path, created_at=img_path.stat().st_mtime)
                        if res and "id" in res:
                            aid = res["id"]
                            status_str = res.get("status", "created")
                            uploaded_ids.append(aid)
                            print(f"   Uploaded: {img_path.name} -> Immich ID: {aid} ({status_str})")
                        else:
                            print(f"   Uploaded: {img_path.name} -> (Response: {res})")

                    if uploaded_ids:
                        client.tag_assets(tag_id, uploaded_ids)
                        print(f"✅ Uploaded and tagged with '{tag_name}' ({len(uploaded_ids)} items)")

                        # Also add to '[Extracted] Photos' album for instant visibility in Immich UI
                        album_name = "[Extracted] Photos"
                        albums = client.get_albums()
                        target_album = next((a for a in albums if a.get("albumName") == album_name), None)
                        if not target_album:
                            target_album = client.create_album(album_name)
                        album_id = target_album["id"]
                        client.add_assets_to_album(album_id, uploaded_ids)
                        print(f"📁 Added {len(uploaded_ids)} images to Album '{album_name}'")

                        # Ensure all assets in the extracted album have the tag applied
                        album_asset_ids = client.get_album_assets(album_id)
                        all_to_tag = list(set(uploaded_ids) | album_asset_ids)
                        client.tag_assets(tag_id, all_to_tag)
                        print(f"🏷  Verified tag '{tag_name}' across all {len(all_to_tag)} assets in '{album_name}'")

    print("✨ Sync operation complete!")


if __name__ == "__main__":
    main()
