"""
immich_static.client — Robust REST API client for Immich server.
"""

import json
import mimetypes
import os
import urllib.error
import urllib.parse
import urllib.request
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Set


class ImmichClient:
    """
    HTTP client for Immich REST API.
    Handles asset searches, album management, tag operations, and asset uploads.
    """
    def __init__(self, base_url: str, api_key: str):
        self.base_url = base_url.rstrip("/")
        self.api_key = api_key
        self.headers = {
            "x-api-key": self.api_key,
            "Accept": "application/json",
            "Content-Type": "application/json",
        }

    def _request(self, method: str, endpoint: str, data: Optional[dict] = None) -> Any:
        url = f"{self.base_url}{endpoint}"
        body = json.dumps(data).encode("utf-8") if data is not None else None
        req = urllib.request.Request(url, data=body, headers=self.headers, method=method)
        try:
            with urllib.request.urlopen(req, timeout=60) as resp:
                resp_text = resp.read().decode("utf-8")
                return json.loads(resp_text) if resp_text else None
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8")
            raise RuntimeError(f"Immich API HTTP {e.code} ({e.reason}) on {method} {endpoint}: {err_body}")
        except Exception as e:
            raise RuntimeError(f"Immich API request failed ({method} {endpoint}): {e}")

    def ping(self) -> dict:
        """Verifies server connectivity and authentication."""
        return self._request("GET", "/api/server/version")

    def get_asset_info(self, asset_id: str) -> Dict[str, Any]:
        """Retrieves detailed metadata for a single asset."""
        return self._request("GET", f"/api/assets/{asset_id}") or {}

    def download_asset(self, asset_id: str, target_path: Path) -> Path:
        """Downloads original asset binary to local target path."""
        url = f"{self.base_url}/api/assets/{asset_id}/original"
        headers = {"x-api-key": self.api_key}
        req = urllib.request.Request(url, headers=headers, method="GET")
        target_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with urllib.request.urlopen(req, timeout=300) as resp, open(target_path, "wb") as out_f:
                while True:
                    chunk = resp.read(1024 * 1024)
                    if not chunk:
                        break
                    out_f.write(chunk)
            return target_path
        except urllib.error.HTTPError as e:
            err_body = e.read().decode("utf-8", errors="ignore")
            raise RuntimeError(f"Immich asset download failed HTTP {e.code}: {err_body}")
        except Exception as e:
            raise RuntimeError(f"Immich asset download failed: {e}")

    def get_all_video_assets(self, verbose: bool = True) -> List[Dict[str, Any]]:
        """Retrieves all video assets from Immich library with pagination."""
        videos = []
        page = 1
        page_size = 1000

        if verbose:
            print("📡 Fetching video catalog from Immich API...")
        while True:
            payload = {
                "type": "VIDEO",
                "size": page_size,
                "page": page,
                "withExif": True,
                "isVisible": True,
            }
            res = self._request("POST", "/api/search/metadata", payload)
            assets = res.get("assets", {}).get("items", []) if isinstance(res, dict) else []
            if not assets:
                break
            videos.extend(assets)
            if len(assets) < page_size:
                break
            page += 1
            if verbose:
                print(f"   Fetched {len(videos)} videos so far (page {page})...")

        if verbose:
            print(f"✅ Found {len(videos)} total video assets in Immich.")
        return videos

    # ─────────────────────────────────────────────
    # ALBUMS API
    # ─────────────────────────────────────────────

    def get_albums(self) -> List[Dict[str, Any]]:
        """Retrieves existing albums."""
        return self._request("GET", "/api/albums") or []

    def get_album(self, album_id: str) -> Dict[str, Any]:
        """Retrieves album details including asset list."""
        return self._request("GET", f"/api/albums/{album_id}") or {}

    def create_album(self, album_name: str) -> Dict[str, Any]:
        """Creates a new album."""
        return self._request("POST", "/api/albums", {"albumName": album_name, "description": "Auto-generated by immich-static"})

    def get_album_assets(self, album_id: str) -> Set[str]:
        """
        Gets all asset IDs currently in an album.
        Supports both legacy direct asset list and modern Immich timeline bucket queries.
        """
        # 1. Try direct album asset list
        try:
            album = self._request("GET", f"/api/albums/{album_id}") or {}
            assets = album.get("assets", [])
            if assets:
                return {a["id"] for a in assets if isinstance(a, dict) and "id" in a}
        except Exception:
            pass

        # 2. Modern Immich API (v1.115+ / v3.x): Timeline buckets query
        asset_ids: Set[str] = set()
        try:
            buckets = self._request("GET", f"/api/timeline/buckets?albumId={album_id}") or []
            if isinstance(buckets, list):
                for b in buckets:
                    tb = b.get("timeBucket") if isinstance(b, dict) else None
                    if not tb:
                        continue
                    b_data = self._request("GET", f"/api/timeline/bucket?albumId={album_id}&timeBucket={tb}") or {}
                    if isinstance(b_data, dict) and "id" in b_data:
                        for aid in b_data["id"]:
                            asset_ids.add(str(aid))
                    elif isinstance(b_data, list):
                        for item in b_data:
                            if isinstance(item, dict) and "id" in item:
                                asset_ids.add(str(item["id"]))
                            elif isinstance(item, str):
                                asset_ids.add(item)
        except Exception:
            pass

        return asset_ids

    def find_parent_motion_photo(self, video_id: str, original_file_name: Optional[str] = None) -> Optional[str]:
        """Finds the parent IMAGE asset ID for a motion photo hidden video."""
        if not original_file_name:
            try:
                info = self._request("GET", f"/api/assets/{video_id}")
                original_file_name = info.get("originalFileName") if isinstance(info, dict) else None
            except Exception:
                pass

        if original_file_name:
            stem = Path(original_file_name).stem
            if stem.endswith(".MV") or stem.endswith("_MP"):
                stem = stem[:-3]
            try:
                res = self._request("POST", "/api/search/metadata", {"originalFileName": stem})
                assets = res.get("assets", {}).get("items", []) if isinstance(res, dict) else []
                for a in assets:
                    if a.get("livePhotoVideoId") == video_id or (a.get("type") == "IMAGE" and stem in a.get("originalFileName", "")):
                        return a.get("id")
            except Exception:
                pass
        return None

    def add_assets_to_album(self, album_id: str, asset_ids: List[str]) -> Tuple[int, List[str]]:
        """
        Adds asset IDs to an album in batches of 500.
        If an asset is rejected because it is a hidden motion photo video companion,
        automatically resolves its parent image asset and adds it instead.
        Returns (added_count, success_asset_ids).
        """
        batch_size = 500
        success_ids: List[str] = []
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            res = self._request("PUT", f"/api/albums/{album_id}/assets", {"ids": batch})
            if isinstance(res, list):
                failed_items = []
                for item in res:
                    if isinstance(item, dict):
                        if item.get("success"):
                            success_ids.append(item.get("id"))
                        else:
                            failed_items.append(item)

                if failed_items:
                    parent_ids_to_retry = []
                    for item in failed_items:
                        vid = item.get("id")
                        if vid:
                            parent_id = self.find_parent_motion_photo(vid)
                            if parent_id:
                                parent_ids_to_retry.append(parent_id)
                    if parent_ids_to_retry:
                        retry_res = self._request("PUT", f"/api/albums/{album_id}/assets", {"ids": parent_ids_to_retry})
                        if isinstance(retry_res, list):
                            for r in retry_res:
                                if isinstance(r, dict) and r.get("success"):
                                    success_ids.append(r.get("id"))
            else:
                success_ids.extend(batch)
        return len(success_ids), success_ids

    def get_assets_total_size(self, asset_ids: Set[str], max_workers: int = 20) -> int:
        """Calculates exact total file size in bytes for a set of asset IDs."""
        if not asset_ids:
            return 0
        from concurrent.futures import ThreadPoolExecutor, as_completed

        def _get_size(aid: str) -> int:
            try:
                info = self._request("GET", f"/api/assets/{aid}")
                exif = info.get("exifInfo") or {}
                return int(exif.get("fileSizeInByte") or info.get("size") or 0)
            except Exception:
                return 0

        total = 0
        workers = min(max_workers, len(asset_ids), 32)
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = [executor.submit(_get_size, aid) for aid in asset_ids]
            for fut in as_completed(futures):
                total += fut.result()
        return total

    # ─────────────────────────────────────────────
    # TAGS API
    # ─────────────────────────────────────────────

    def get_tags(self) -> List[Dict[str, Any]]:
        """Retrieves all tags."""
        try:
            return self._request("GET", "/api/tags") or []
        except Exception:
            return []

    def create_tag(self, tag_name: str) -> Dict[str, Any]:
        """Creates a new tag."""
        try:
            return self._request("POST", "/api/tags", {"name": tag_name, "type": "CUSTOM"})
        except Exception:
            return self._request("POST", "/api/tags", {"name": tag_name})

    def untag_assets(self, tag_id: str, asset_ids: List[str]):
        """Removes a tag from asset IDs in batches."""
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            try:
                self._request("DELETE", f"/api/tags/{tag_id}/assets", {"ids": batch})
            except Exception:
                pass

    def tag_assets(self, tag_id: str, asset_ids: List[str]):
        """Tags asset IDs in batches of 500 with response verification and retry."""
        import time
        batch_size = 500
        for i in range(0, len(asset_ids), batch_size):
            batch = asset_ids[i:i + batch_size]
            res = None
            try:
                res = self._request("PUT", f"/api/tags/{tag_id}/assets", {"ids": batch})
            except Exception:
                try:
                    res = self._request("POST", f"/api/tags/{tag_id}/assets", {"ids": batch})
                except Exception as e:
                    print(f"⚠️  Tag request error: {e}")

            if isinstance(res, list):
                failed = [
                    item.get("id") for item in res
                    if isinstance(item, dict) and not item.get("success", True) and item.get("id")
                ]
                if failed:
                    time.sleep(1.0)
                    try:
                        self._request("PUT", f"/api/tags/{tag_id}/assets", {"ids": failed})
                    except Exception:
                        pass

    def upload_asset(self, file_path: Path, created_at: Optional[Any] = None) -> Optional[Dict[str, Any]]:
        """Uploads a still frame image to Immich multipart/form-data."""
        boundary = f"----WebKitFormBoundary{uuid.uuid4().hex}"
        filename = file_path.name
        mime_type = mimetypes.guess_type(str(file_path))[0] or "image/jpeg"
        with open(file_path, "rb") as f:
            file_data = f.read()

        if created_at:
            try:
                if isinstance(created_at, (int, float)):
                    dt = datetime.fromtimestamp(created_at, tz=timezone.utc)
                    utc_time_str = dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
                else:
                    dt = datetime.fromisoformat(str(created_at).replace("Z", "+00:00")).astimezone(timezone.utc)
                    utc_time_str = dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")
            except Exception:
                utc_time_str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
        else:
            utc_time_str = datetime.fromtimestamp(file_path.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

        device_asset_id = f"{file_path.stem}-{uuid.uuid4().hex[:8]}"

        parts = []
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"deviceAssetId\"\r\n\r\n{device_asset_id}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"deviceId\"\r\n\r\nimmich-static\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileCreatedAt\"\r\n\r\n{utc_time_str}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"fileModifiedAt\"\r\n\r\n{utc_time_str}\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"isFavorite\"\r\n\r\nfalse\r\n".encode("utf-8"))
        parts.append(f"--{boundary}\r\nContent-Disposition: form-data; name=\"assetData\"; filename=\"{filename}\"\r\nContent-Type: {mime_type}\r\n\r\n".encode("utf-8"))
        parts.append(file_data)
        parts.append(f"\r\n--{boundary}--\r\n".encode("utf-8"))

        body = b"".join(parts)
        headers = {
            "x-api-key": self.api_key,
            "Content-Type": f"multipart/form-data; boundary={boundary}",
            "Accept": "application/json",
        }
        url = f"{self.base_url}/api/assets"
        req = urllib.request.Request(url, data=body, headers=headers, method="POST")
        try:
            with urllib.request.urlopen(req, timeout=120) as resp:
                res_text = resp.read().decode("utf-8")
                return json.loads(res_text) if res_text else None
        except urllib.error.HTTPError as e:
            err_msg = e.read().decode("utf-8")
            raise RuntimeError(f"Immich upload failed ({e.code} {e.reason}): {err_msg}")
        except Exception as e:
            raise RuntimeError(f"Immich upload request failed: {e}")
